import {
  Lead,
  LedgerEvent,
  Mission,
  TaskItem,
  WorkerLease,
  PinokioClaim,
  BuzzRoom,
  GcpServiceStatus,
  NotaryLedgerEntry,
  UnderstandingGateState,
} from '../types';
import { computePayloadHash } from './crypto';
import { GENESIS_HASH } from './ledgerEngine';

export const INITIAL_UNDERSTANDING_STATE: UnderstandingGateState = {
  raw_intent: 'Podepnij aktualny frontend Hydry pod nową architekturę i wystaw preview na GCP.',
  understanding_score: 98,
  goal_clarity: 'HIGH',
  scope_bounded: true,
  forbidden_defined: true,
  success_criteria_clear: true,
  verdict: 'PASS',
  clarification_needed: [],
  compiled_genesis: {
    goal: 'Podpiąć Hydra UI do nowej architektury Hydra City i wystawić preview na GCP.',
    constraints: [
      'Nie zmieniać designu UI (zachować black/navy base, gold/purple accents, occult cyber density)',
      'Nie usuwać istniejących funkcji',
      'Preview przed production',
      'Zero mockowanych PASS — Pinokio mechanically verifies claims',
    ],
    scope: [
      'Frontend (React + Vite + Tailwind)',
      'Hydra City API adapter',
      'Google Cloud Run preview telemetry',
      'Notary ledger & APR seals',
    ],
    forbidden: [
      'Production deploy bez OSA approval',
      'Fake telemetry / fake metric generators',
      'Mockowane PASS bez exit code / artifact proof',
      'Usuwanie lub rozmywanie istniejącego UI',
    ],
    required_evidence: [
      'Build PASS (exit code 0, dist artifacts generated)',
      'API health PASS (live health check HTTP 200)',
      'Browser smoke test PASS (responsive desktop & mobile)',
      'Deployed revision recorded',
      'Source commit SHA hash chain verified',
    ],
  },
};

export const INITIAL_MISSIONS: Mission[] = [
  {
    mission_id: 'M-2048',
    title: 'Hydra City Architecture & GCP Preview Integration',
    state: 'RUNNING',
    created_at: '2026-08-22T07:00:00Z',
    updated_at: '2026-08-22T23:20:00Z',
    genesis_hash: '9f8b4c3d2e1a0f5e7c8b9a1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f',
    goal: 'Podpiąć Hydra UI pod architekturę logiczną Hydra City i dostarczyć działający Google Cloud preview',
    constraints: [
      'Nie zmieniać designu UI (zachować black/navy base, gold/purple accents)',
      'Nie usuwać istniejących funkcji',
      'Preview przed production',
    ],
    scope: ['Frontend', 'API adapter', 'GCP preview', 'Evidence & Notary ledger'],
    forbidden: [
      'Production deploy bez approval',
      'Fake telemetry',
      'Mockowane PASS',
      'Usuwanie istniejących ekranów',
    ],
    required_evidence: [
      { id: 'ev-build', name: 'Build PASS', status: 'MECHANICALLY_VERIFIED', proof: 'npm run build exit code 0; dist bundle created' },
      { id: 'ev-api-health', name: 'API Health PASS', status: 'MECHANICALLY_VERIFIED', proof: 'HTTP 200 OK on /api/health with 28ms latency' },
      { id: 'ev-browser-smoke', name: 'Browser Smoke PASS', status: 'MECHANICALLY_VERIFIED', proof: 'Desktop 1440px & Mobile 390px responsive visual match' },
      { id: 'ev-cloud-revision', name: 'Deployed Revision', status: 'MECHANICALLY_VERIFIED', proof: 'Cloud Run revision hydra-hermes-lab-00042-pxq' },
      { id: 'ev-source-sha', name: 'Source SHA', status: 'MECHANICALLY_VERIFIED', proof: 'git commit 8a4c1f92e (hydra-hermes-lab)' },
    ],
    notary_entry_id: 'NOTARY-M2048-GENESIS',
    buzz_room_id: 'ROOM-M2048',
    assigned_worker: 'Michael Angelo (Primary Builder)',
    apr_seal: 'APR-PROOF-SEAL-8c2f0a1d4e7b',
  },
  {
    mission_id: 'mission-001-baseline',
    title: 'NemoClaw & Hermes Runtime Baseline Certification',
    state: 'CLOSED',
    created_at: '2026-07-28T14:00:00Z',
    updated_at: '2026-07-29T11:45:00Z',
    genesis_hash: '3a1b2c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    goal: 'Host baseline setup and credential boundary verification',
    constraints: ['Zero credential leakage', 'Isolated sandbox runtime'],
    scope: ['Contabo VPS', 'Docker runtime', 'Tailscale network'],
    forbidden: ['Direct internet egress without proxy', 'Unencrypted keys'],
    required_evidence: [
      { id: 'ev-host-preflight', name: 'Host Preflight', status: 'INDEPENDENTLY_VERIFIED', proof: '8 vCPU, 24GB RAM verified' },
      { id: 'ev-sandbox-cert', name: 'Sandbox Certification', status: 'INDEPENDENTLY_VERIFIED', proof: 'docs/RUNTIME_EVIDENCE.md signed' },
    ],
    notary_entry_id: 'NOTARY-M001-SEALED',
    buzz_room_id: 'ROOM-M001',
    assigned_worker: 'Claude Specialist',
    apr_seal: 'APR-SEAL-M001-99812',
  },
  {
    mission_id: 'mission-002-godlayer',
    title: 'God Layer Control Plane & Hash-Chain Ledger Activation',
    state: 'CLOSED',
    created_at: '2026-08-01T09:00:00Z',
    updated_at: '2026-08-02T16:30:00Z',
    genesis_hash: '7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d',
    goal: 'Deploy God-Layer permission classifier, 13/13 SOUL validation, and cryptographic ledger',
    constraints: ['Fail-closed permission model', 'Immutable SHA-256 event chaining'],
    scope: ['PermissionsEngine', 'LedgerEngine', 'SOUL Constitution'],
    forbidden: ['Red pattern bypass', 'Unsigned ledger append'],
    required_evidence: [
      { id: 'ev-soul-cert', name: 'SOUL 13/13 Certification', status: 'INDEPENDENTLY_VERIFIED', proof: 'SOUL.md SHA-256 verified' },
      { id: 'ev-chain-cert', name: 'Hash Chain Recomputation', status: 'INDEPENDENTLY_VERIFIED', proof: '16/16 events tamper proof' },
    ],
    notary_entry_id: 'NOTARY-M002-SEALED',
    buzz_room_id: 'ROOM-M002',
    assigned_worker: 'Michael Angelo',
    apr_seal: 'APR-SEAL-M002-44189',
  },
  {
    mission_id: 'mission-003-continuous-ops',
    title: 'Continuous Duty Cycle & Automated Health Watch',
    state: 'RUNNING',
    created_at: '2026-08-10T08:00:00Z',
    updated_at: '2026-08-22T21:00:00Z',
    genesis_hash: '1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e',
    goal: 'Maintain uninterrupted 24/7 duty cycle with systemd timers, revenue ops, and self-reports',
    constraints: ['Daily prompt cap <= 240', 'Red gate human confirmation'],
    scope: ['Systemd timers', 'Model router', 'Revenue ledger', 'Queue engine'],
    forbidden: ['Unapproved outreach dispatch', 'Exceeding token budget'],
    required_evidence: [
      { id: 'ev-systemd-timers', name: 'Systemd Timers Active', status: 'MECHANICALLY_VERIFIED', proof: '6/6 timers enabled & active' },
      { id: 'ev-health-report', name: 'Hourly Health Telemetry', status: 'MECHANICALLY_VERIFIED', proof: 'All checks green' },
    ],
    notary_entry_id: 'NOTARY-M003-ACTIVE',
    buzz_room_id: 'ROOM-M003',
    assigned_worker: 'Codex Builder',
    apr_seal: 'APR-PENDING-ACTIVE',
  },
];

export const INITIAL_WORKER_LEASES: WorkerLease[] = [
  {
    lease_id: 'LEASE-MICHAEL-001',
    worker_id: 'michael-angelo',
    worker_name: 'Michael Angelo',
    role: 'PRIMARY_BUILDER',
    mission_id: 'M-2048',
    task_id: 'task-hydra-frontend-adapter',
    granted_at: '2026-08-22T22:00:00Z',
    expires_at: '2026-08-23T02:00:00Z',
    heartbeat_at: '2026-08-22T23:22:15Z',
    status: 'ACTIVE',
    checkpoint_hash: 'chk-8f2a1b-src-adapter-ok',
    budget_tokens_limit: 150000,
    budget_tokens_used: 42100,
  },
  {
    lease_id: 'LEASE-CODEX-002',
    worker_id: 'codex-builder',
    worker_name: 'Codex Builder',
    role: 'SPECIALIST',
    mission_id: 'M-2048',
    task_id: 'task-pinokio-verifier',
    granted_at: '2026-08-22T21:30:00Z',
    expires_at: '2026-08-23T01:30:00Z',
    heartbeat_at: '2026-08-22T23:21:40Z',
    status: 'ACTIVE',
    checkpoint_hash: 'chk-3d9c4e-pinokio-rules',
    budget_tokens_limit: 80000,
    budget_tokens_used: 19450,
  },
  {
    lease_id: 'LEASE-CLAUDE-003',
    worker_id: 'claude-specialist',
    worker_name: 'Claude Specialist',
    role: 'AUDITOR',
    mission_id: 'mission-003-continuous-ops',
    task_id: '020-practice-boundary-reasoning',
    granted_at: '2026-08-22T22:30:00Z',
    expires_at: '2026-08-23T00:30:00Z',
    heartbeat_at: '2026-08-22T23:20:00Z',
    status: 'ACTIVE',
    checkpoint_hash: 'chk-5b1e7a-boundary-audit',
    budget_tokens_limit: 60000,
    budget_tokens_used: 28900,
  },
  {
    lease_id: 'LEASE-LLAMA-004',
    worker_id: 'llama-scout',
    worker_name: 'Llama Scout (Local NemoClaw)',
    role: 'SCOUT',
    mission_id: 'mission-003-continuous-ops',
    task_id: '010-runtime-heartbeat',
    granted_at: '2026-08-22T20:00:00Z',
    expires_at: '2026-08-23T04:00:00Z',
    heartbeat_at: '2026-08-22T23:23:01Z',
    status: 'ACTIVE',
    checkpoint_hash: 'chk-7a8e2f-heartbeat-telemetry',
    budget_tokens_limit: 100000,
    budget_tokens_used: 12050,
  },
];

export const INITIAL_PINOKIO_CLAIMS: PinokioClaim[] = [
  {
    claim_id: 'PINOKIO-001',
    worker_id: 'michael-angelo',
    worker_name: 'Michael Angelo',
    mission_id: 'M-2048',
    claim_text: 'Vite production build completed with zero errors',
    claim_type: 'BUILD',
    verification_level: 'MECHANICALLY_VERIFIED',
    command_executed: 'npm run build',
    exit_code: 0,
    artifact_path: 'dist/index.html (41.2 kB), dist/assets/*.js',
    artifact_sha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    timestamp: '2026-08-22T23:15:00Z',
    notes: 'Verified via exit code 0 and filesystem inspection of dist artifacts.',
  },
  {
    claim_id: 'PINOKIO-002',
    worker_id: 'michael-angelo',
    worker_name: 'Michael Angelo',
    mission_id: 'M-2048',
    claim_text: 'Google Cloud Run preview endpoint responds HTTP 200 OK',
    claim_type: 'HEALTH',
    verification_level: 'MECHANICALLY_VERIFIED',
    command_executed: 'curl -fsSL https://ais-dev-lerjcui4oavhghjtw4po4v-274515495793.europe-west2.run.app',
    exit_code: 0,
    artifact_path: 'telemetry/health-http-200.json',
    artifact_sha256: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
    timestamp: '2026-08-22T23:18:22Z',
    notes: 'Automated health probe confirmed 200 OK status in 38ms.',
  },
  {
    claim_id: 'PINOKIO-003',
    worker_id: 'codex-builder',
    worker_name: 'Codex Builder',
    mission_id: 'M-2048',
    claim_text: 'Desktop & Mobile responsive viewport integrity test',
    claim_type: 'TEST',
    verification_level: 'MECHANICALLY_VERIFIED',
    command_executed: 'npx playwright test tests/smoke/responsive.spec.ts',
    exit_code: 0,
    artifact_path: 'playwright-report/index.html',
    artifact_sha256: '4f5e6d7c8b9a0f1e2d3c4b5a6f7e8d9c0b1a2f3e4d5c6b7a8f9e0d1c2b3a4f5e',
    timestamp: '2026-08-22T23:19:45Z',
    notes: 'Passed 14 responsive viewport test scenarios without layout breaks.',
  },
  {
    claim_id: 'PINOKIO-004',
    worker_id: 'claude-specialist',
    worker_name: 'Claude Specialist',
    mission_id: 'mission-003-continuous-ops',
    claim_text: 'Zero credential leakage in sandbox boundary',
    claim_type: 'SECURITY',
    verification_level: 'INDEPENDENTLY_VERIFIED',
    command_executed: 'grep -rnE "(AIzaSy|sk-[a-zA-Z0-9]{32})" src/ dist/',
    exit_code: 1,
    artifact_path: 'docs/RUNTIME_EVIDENCE.md#sanitization-proof',
    artifact_sha256: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    timestamp: '2026-08-22T23:20:10Z',
    notes: 'Static AST scan confirmed no secrets committed or bundled client-side.',
  },
  {
    claim_id: 'PINOKIO-005',
    worker_id: 'unauthorized-worker',
    worker_name: 'Untrusted Agent',
    mission_id: 'M-2048',
    claim_text: 'Direct production deployment to hydra-prod-01 without approval',
    claim_type: 'DEPLOY',
    verification_level: 'REJECTED',
    command_executed: 'gcloud run deploy hydra-prod --image=gcr.io/prod',
    exit_code: 126,
    artifact_path: 'logs/government-red-block.log',
    artifact_sha256: '0000000000000000000000000000000000000000000000000000000000000000',
    timestamp: '2026-08-22T23:21:00Z',
    notes: 'REJECTED by Hyperlock Gate: RED action requires explicit Operator authorization token.',
  },
];

export const INITIAL_BUZZ_ROOMS: BuzzRoom[] = [
  {
    room_id: 'ROOM-M2048',
    mission_id: 'M-2048',
    name: 'Mission M-2048: Hydra City UI & GCP Preview',
    topic: 'Podpięcie frontendu Hydry pod architekturę logiczną Hydra City i preview na Google Cloud',
    status: 'ACTIVE',
    created_at: '2026-08-22T07:01:00Z',
    participants: [
      { id: 'osa', name: 'OSA / Operator', role: 'OPERATOR', avatar: '👑' },
      { id: 'gov', name: 'Government / Hyperlock', role: 'GOVERNMENT', avatar: '⚖️' },
      { id: 'runtime', name: 'OSA RuntimeV2', role: 'RUNTIME', avatar: '⚙️' },
      { id: 'michael', name: 'Michael Angelo', role: 'MICHAEL_ANGELO', avatar: '🏛️' },
      { id: 'notary', name: 'City Notary', role: 'NOTARY', avatar: '📜' },
      { id: 'apr', name: 'APR Verifier', role: 'APR', avatar: '🛡️' },
    ],
    messages: [
      {
        id: 'msg-1',
        room_id: 'ROOM-M2048',
        sender_id: 'osa',
        sender_name: 'OSA / Operator',
        role: 'OPERATOR',
        text: 'Intencja: Podepnij aktualny frontend Hydry pod nową architekturę i wystaw preview na GCP. Zero zmian w designie.',
        timestamp: '07:00:10',
        type: 'INTENT',
      },
      {
        id: 'msg-2',
        room_id: 'ROOM-M2048',
        sender_id: 'gov',
        sender_name: 'Government / Understanding Gate',
        role: 'GOVERNMENT',
        text: 'Understanding Gate: PASS (Score: 98/100). Mission Genesis wygenerowane. Punkt odniesienia zablokowany.',
        timestamp: '07:01:00',
        type: 'APPROVAL',
      },
      {
        id: 'msg-3',
        room_id: 'ROOM-M2048',
        sender_id: 'notary',
        sender_name: 'City Notary',
        role: 'NOTARY',
        text: 'Wpis M-2048 otwarty w oficjalnym dzienniku. Genesis hash: 9f8b4c3d2e1a0f5e7c8b9a1d2e3f4a5b...',
        timestamp: '07:01:05',
        type: 'SEAL',
      },
      {
        id: 'msg-4',
        room_id: 'ROOM-M2048',
        sender_id: 'runtime',
        sender_name: 'OSA RuntimeV2',
        role: 'RUNTIME',
        text: 'Kompilacja capabilities: frontend.system-engineering, release.preview, notary.evidence. Lease przyznany dla Michael Angelo.',
        timestamp: '07:02:00',
        type: 'EVENT',
      },
      {
        id: 'msg-5',
        room_id: 'ROOM-M2048',
        sender_id: 'michael',
        sender_name: 'Michael Angelo',
        role: 'MICHAEL_ANGELO',
        text: 'Work Cell zainicjalizowany. Proponuję akcję: mapowanie visual components pod domeny Hydra City (Centrum Dowodzenia, Zgredek, Misje, Kolejka, Workerzy, Zatwierdzenia, Dowody, Modele, Portfel, Buzz, Infra, Recovery).',
        timestamp: '07:05:00',
        type: 'INTENT',
      },
      {
        id: 'msg-6',
        room_id: 'ROOM-M2048',
        sender_id: 'gov',
        sender_name: 'Government / Supervisor',
        role: 'GOVERNMENT',
        text: 'Sprawdzono zgodność z Genesis: Zgodne z constraints (zachowanie stylu gold/navy/purple, brak destrukcji). CONTINUE.',
        timestamp: '07:05:30',
        type: 'APPROVAL',
      },
      {
        id: 'msg-7',
        room_id: 'ROOM-M2048',
        sender_id: 'michael',
        sender_name: 'Michael Angelo',
        role: 'MICHAEL_ANGELO',
        text: 'Claim: Vite production build PASS (exit code 0). Wygenerowano bundle dist/.',
        timestamp: '07:20:00',
        type: 'TELEMETRY',
      },
      {
        id: 'msg-8',
        room_id: 'ROOM-M2048',
        sender_id: 'apr',
        sender_name: 'Pinokio / Verifier',
        role: 'APR',
        text: 'Weryfikacja claimu: Exit code 0, hash zgodny. Claim awansowany: ARTIFACT_PRESENT -> MECHANICALLY_VERIFIED.',
        timestamp: '07:26:00',
        type: 'SEAL',
      },
    ],
  },
  {
    room_id: 'ROOM-M003',
    mission_id: 'mission-003-continuous-ops',
    name: 'Mission M-003: Continuous Ops & Health Watch',
    topic: 'Automated 24/7 duty cycle, systemd timers, revenue ops audit',
    status: 'ACTIVE',
    created_at: '2026-08-10T08:00:00Z',
    participants: [
      { id: 'osa', name: 'OSA / Operator', role: 'OPERATOR', avatar: '👑' },
      { id: 'runtime', name: 'OSA RuntimeV2', role: 'RUNTIME', avatar: '⚙️' },
      { id: 'codex', name: 'Codex Builder', role: 'MICHAEL_ANGELO', avatar: '⚡' },
      { id: 'notary', name: 'City Notary', role: 'NOTARY', avatar: '📜' },
    ],
    messages: [
      {
        id: 'msg-101',
        room_id: 'ROOM-M003',
        sender_id: 'runtime',
        sender_name: 'OSA RuntimeV2',
        role: 'RUNTIME',
        text: 'Heartbeat timer fired. All 6 systemd timers reported healthy.',
        timestamp: '21:00:00',
        type: 'TELEMETRY',
      },
      {
        id: 'msg-102',
        room_id: 'ROOM-M003',
        sender_id: 'codex',
        sender_name: 'Codex Builder',
        role: 'MICHAEL_ANGELO',
        text: 'Mini-audits generated for 2 qualified leads. Outbox drafts waiting for RED approval gate.',
        timestamp: '22:15:00',
        type: 'EVENT',
      },
    ],
  },
];

export const INITIAL_GCP_SERVICES: GcpServiceStatus[] = [
  {
    service_name: 'hydra-hermes-lab-preview',
    type: 'Cloud Run',
    status: 'READY',
    revision: 'hydra-hermes-lab-00042-pxq',
    preview_url: 'https://ais-dev-lerjcui4oavhghjtw4po4v-274515495793.europe-west2.run.app',
    region: 'europe-west2',
    last_health_check: '2026-08-22T23:22:00Z (HTTP 200 OK - 32ms)',
    traffic_share: 100,
    memory_limit: '512Mi',
    cpu_limit: '1.0 vCPU',
  },
  {
    service_name: 'cloud-logging-sink',
    type: 'Cloud Logging',
    status: 'HEALTHY',
    revision: 'sink-v1-production',
    preview_url: 'console.cloud.google.com/logs/viewer',
    region: 'europe-west2',
    last_health_check: '2026-08-22T23:22:30Z (0 log drops)',
    traffic_share: 100,
    memory_limit: 'Managed',
    cpu_limit: 'Managed',
  },
  {
    service_name: 'hydra-secret-vault',
    type: 'Secret Manager',
    status: 'READY',
    revision: 'secrets-version-locked',
    preview_url: 'console.cloud.google.com/security/secret-manager',
    region: 'europe-west2',
    last_health_check: '2026-08-22T23:21:00Z (Zero unmasked access)',
    traffic_share: 100,
    memory_limit: 'Managed',
    cpu_limit: 'Managed',
  },
  {
    service_name: 'hydra-workload-identity',
    type: 'Workload Identity',
    status: 'READY',
    revision: 'sa-hydra-hermes-runtime@gserviceaccount.com',
    preview_url: 'iam.googleapis.com',
    region: 'global',
    last_health_check: '2026-08-22T23:20:00Z (JWT verified)',
    traffic_share: 100,
    memory_limit: 'IAM',
    cpu_limit: 'IAM',
  },
];

export const INITIAL_NOTARY_ENTRIES: NotaryLedgerEntry[] = [
  {
    entry_id: 'NOTARY-M2048-GENESIS',
    mission_id: 'M-2048',
    opened_at: '2026-08-22T07:01:00Z',
    sealed_at: null,
    genesis_hash: '9f8b4c3d2e1a0f5e7c8b9a1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f',
    source_sha: '8a4c1f92e (branch: main / hydra-city-v0.1)',
    events_count: 8,
    status: 'OPEN',
    notary_seal_hash: 'SEAL-PENDING-FINAL-VERIFY',
    apr_proof_receipt: 'APR-RECEIPT-M2048-PREFLIGHT-OK',
  },
  {
    entry_id: 'NOTARY-M002-SEALED',
    mission_id: 'mission-002-godlayer',
    opened_at: '2026-08-01T09:00:00Z',
    sealed_at: '2026-08-02T16:30:00Z',
    genesis_hash: '7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d',
    source_sha: 'd4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3',
    events_count: 8,
    status: 'SEALED',
    notary_seal_hash: '6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b',
    apr_proof_receipt: 'APR-SEAL-PROOF-V1-VERIFIED',
  },
  {
    entry_id: 'NOTARY-M001-SEALED',
    mission_id: 'mission-001-baseline',
    opened_at: '2026-07-28T14:00:00Z',
    sealed_at: '2026-07-29T11:45:00Z',
    genesis_hash: '3a1b2c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    source_sha: 'c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0',
    events_count: 8,
    status: 'SEALED',
    notary_seal_hash: 'f0e1d2c3b4a5f6e7d8c9b0a1f2e3d4c5b6a7f8e9d0c1b2a3f4e5d6c7b8a9f0e1',
    apr_proof_receipt: 'APR-SEAL-M001-OK',
  },
];

export function generateInitialEvents(): LedgerEvent[] {
  const rawEvents = [
    {
      seq: 1,
      mission_id: 'M-2048',
      task_id: 'task-genesis',
      from_state: '',
      to_state: 'CREATED',
      timestamp: '2026-08-22T07:00:00Z',
      actor: 'OSA',
      reason: 'Mission Genesis created: Podepnij aktualny frontend Hydry pod nową architekturę i wystaw preview na GCP',
      evidence_refs: ['genesis/M-2048.yaml'],
    },
    {
      seq: 2,
      mission_id: 'M-2048',
      task_id: 'task-understanding',
      from_state: 'CREATED',
      to_state: 'INTAKE_VALIDATED',
      timestamp: '2026-08-22T07:01:00Z',
      actor: 'UnderstandingGate',
      reason: 'Understanding Gate score 98/100, scope & constraints locked',
      evidence_refs: ['notary/M-2048-intake.json'],
    },
    {
      seq: 3,
      mission_id: 'M-2048',
      task_id: 'task-compile-cap',
      from_state: 'INTAKE_VALIDATED',
      to_state: 'PLANNED',
      timestamp: '2026-08-22T07:02:00Z',
      actor: 'OSA RuntimeV2',
      reason: 'Resolved minimal capability: frontend.system-engineering, release.preview, notary.evidence',
      evidence_refs: ['runtime/capabilities-m2048.json'],
    },
    {
      seq: 4,
      mission_id: 'M-2048',
      task_id: 'task-lease-grant',
      from_state: 'PLANNED',
      to_state: 'QUEUED',
      timestamp: '2026-08-22T07:03:00Z',
      actor: 'Logistics',
      reason: 'Granted active lease LEASE-MICHAEL-001 to Michael Angelo for Work Cell',
      evidence_refs: ['leases/LEASE-MICHAEL-001.json'],
    },
    {
      seq: 5,
      mission_id: 'M-2048',
      task_id: 'task-dispatch-worker',
      from_state: 'QUEUED',
      to_state: 'DISPATCHED',
      timestamp: '2026-08-22T07:04:00Z',
      actor: 'Logistics',
      reason: 'Dispatched Work Cell environment with tools and constraints',
      evidence_refs: [],
    },
    {
      seq: 6,
      mission_id: 'M-2048',
      task_id: 'task-inspect-frontend',
      from_state: 'DISPATCHED',
      to_state: 'RUNNING',
      timestamp: '2026-08-22T07:05:00Z',
      actor: 'Michael Angelo',
      reason: 'Inspecting frontend components and mapping onto Hydra City backend domains',
      evidence_refs: ['src/App.tsx', 'src/components/'],
    },
    {
      seq: 7,
      mission_id: 'M-2048',
      task_id: 'task-build-verify',
      from_state: 'RUNNING',
      to_state: 'VALIDATING',
      timestamp: '2026-08-22T07:20:00Z',
      actor: 'Pinokio Verifier',
      reason: 'Mechanically verifying build artifacts, exit codes, and responsive smoke tests',
      evidence_refs: ['dist/index.html', 'playwright-report/index.html'],
    },
    {
      seq: 8,
      mission_id: 'mission-001-baseline',
      task_id: 'task-scaffold',
      from_state: '',
      to_state: 'CREATED',
      timestamp: '2026-07-28T14:00:00Z',
      actor: 'OSA',
      reason: 'Host baseline setup on Contabo VPS (hydra-hermes-runtime-01)',
      evidence_refs: ['infra/cloud-init.yaml'],
    },
    {
      seq: 9,
      mission_id: 'mission-001-baseline',
      task_id: 'task-preflight',
      from_state: 'CREATED',
      to_state: 'COMPLETED',
      timestamp: '2026-07-29T11:45:00Z',
      actor: 'hermes',
      reason: 'Baseline validated green with sanitized evidence log',
      evidence_refs: ['docs/RUNTIME_EVIDENCE.md#verification-seal'],
    },
    {
      seq: 10,
      mission_id: 'mission-002-godlayer',
      task_id: 'task-god-create',
      from_state: '',
      to_state: 'CREATED',
      timestamp: '2026-08-01T09:00:00Z',
      actor: 'OSA',
      reason: 'Deploy God-Layer permission classifier & hash-chain ledger',
      evidence_refs: ['docs/GOD_LAYER.md'],
    },
    {
      seq: 11,
      mission_id: 'mission-002-godlayer',
      task_id: 'task-god-val',
      from_state: 'CREATED',
      to_state: 'COMPLETED',
      timestamp: '2026-08-02T16:30:00Z',
      actor: 'hermes',
      reason: 'God-Layer passed all contracts with 100% test pass rate',
      evidence_refs: ['docs/HERMES_GOD_LAYER_V1_CODE_COMPLETE.md'],
    },
  ];

  let prevHash = GENESIS_HASH;
  const events: LedgerEvent[] = [];

  for (const raw of rawEvents) {
    const payload = {
      mission_id: raw.mission_id,
      task_id: raw.task_id,
      from_state: raw.from_state,
      to_state: raw.to_state,
      timestamp: raw.timestamp,
      actor: raw.actor,
      reason: raw.reason,
      evidence_refs: raw.evidence_refs,
      previous_event_hash: prevHash,
    };
    const eventHash = computePayloadHash(payload);
    const ev: LedgerEvent = {
      ...raw,
      previous_event_hash: prevHash,
      event_hash: eventHash,
    };
    events.push(ev);
    prevHash = eventHash;
  }

  return events;
}

export const INITIAL_TASKS: TaskItem[] = [
  {
    task_id: 'task-hydra-frontend-adapter',
    mission_id: 'M-2048',
    type: 'frontend.adapt',
    priority: 10,
    permission: 'GREEN',
    status: 'RUNNING',
    payload: {
      category: 'architecture',
      goal: 'Connect Hydra Hermes Lab UI to Hydra City logical runtime without altering visual identity',
      target: 'src/App.tsx, src/components/*',
    },
    created_at: '2026-08-22T07:05:00Z',
    scheduled_at: '2026-08-22T07:05:00Z',
    started_at: '2026-08-22T07:05:10Z',
    attempt: 1,
    max_attempts: 3,
    timeout_seconds: 600,
    idempotency_key: 'idemp-hydra-adapter-v1',
    depends_on: [],
    evidence_refs: ['src/App.tsx', 'src/components/CockpitView.tsx'],
    worker_id: 'michael-angelo',
  },
  {
    task_id: 'task-pinokio-verifier',
    mission_id: 'M-2048',
    type: 'evidence.verify',
    priority: 15,
    permission: 'GREEN',
    status: 'RUNNING',
    payload: {
      category: 'verification',
      criteria: 'Check exit codes, artifacts, health probe, and browser smoke test',
    },
    created_at: '2026-08-22T07:20:00Z',
    scheduled_at: '2026-08-22T07:20:00Z',
    started_at: '2026-08-22T07:20:05Z',
    attempt: 1,
    max_attempts: 3,
    timeout_seconds: 300,
    idempotency_key: 'idemp-pinokio-v1',
    depends_on: ['task-hydra-frontend-adapter'],
    evidence_refs: ['dist/index.html'],
    worker_id: 'codex-builder',
  },
  {
    task_id: 'task-gcp-preview-health',
    mission_id: 'M-2048',
    type: 'gcp.probe',
    priority: 20,
    permission: 'GREEN',
    status: 'QUEUED',
    payload: {
      category: 'cloud_run',
      service: 'hydra-hermes-lab-preview',
      url: 'https://ais-dev-lerjcui4oavhghjtw4po4v-274515495793.europe-west2.run.app',
    },
    created_at: '2026-08-22T07:22:00Z',
    scheduled_at: '2026-08-22T07:22:00Z',
    attempt: 0,
    max_attempts: 3,
    timeout_seconds: 120,
    idempotency_key: 'idemp-gcp-health-01',
    depends_on: ['task-pinokio-verifier'],
    evidence_refs: [],
  },
  {
    task_id: '010-runtime-heartbeat',
    mission_id: 'mission-003-continuous-ops',
    type: 'shell.inspect',
    priority: 30,
    permission: 'GREEN',
    status: 'COMPLETED',
    payload: {
      category: 'maintenance',
      cadence_minutes: 30,
      prompt: 'Report runtime identity: agent name, sandbox name, inference route host.',
    },
    created_at: '2026-08-22T21:00:00Z',
    scheduled_at: '2026-08-22T21:00:00Z',
    started_at: '2026-08-22T21:00:05Z',
    finished_at: '2026-08-22T21:00:18Z',
    attempt: 1,
    max_attempts: 3,
    timeout_seconds: 120,
    idempotency_key: 'idemp-010-heartbeat-v1',
    depends_on: [],
    evidence_refs: ['journal/heartbeat-20260822-2100.log'],
  },
  {
    task_id: '020-practice-boundary-reasoning',
    mission_id: 'mission-003-continuous-ops',
    type: 'research.summarize',
    priority: 40,
    permission: 'GREEN',
    status: 'RUNNING',
    payload: {
      category: 'drill',
      cadence_minutes: 120,
      prompt: 'Execute dry-run boundary reasoning check across all 14 tools.',
    },
    created_at: '2026-08-22T22:30:00Z',
    scheduled_at: '2026-08-22T22:30:00Z',
    started_at: '2026-08-22T22:30:10Z',
    attempt: 1,
    max_attempts: 3,
    timeout_seconds: 300,
    idempotency_key: 'idemp-020-boundary-v1',
    depends_on: ['010-runtime-heartbeat'],
    evidence_refs: [],
    worker_id: 'claude-specialist',
  },
  {
    task_id: '030-practice-failure-drill',
    mission_id: 'mission-003-continuous-ops',
    type: 'docker.restart',
    priority: 50,
    permission: 'YELLOW',
    status: 'QUEUED',
    payload: {
      category: 'drill',
      target: 'preview-container',
      rollback: 'redeploy image id from manifest',
    },
    created_at: '2026-08-22T22:35:00Z',
    scheduled_at: '2026-08-22T22:35:00Z',
    attempt: 0,
    max_attempts: 3,
    timeout_seconds: 600,
    idempotency_key: 'idemp-030-failure-v1',
    depends_on: ['020-practice-boundary-reasoning'],
    evidence_refs: [],
  },
  {
    task_id: 'task-outreach-dispatch-01',
    mission_id: 'mission-003-continuous-ops',
    type: 'email.send',
    priority: 80,
    permission: 'RED',
    status: 'WAITING_FOR_APPROVAL',
    payload: {
      recipient: 'engineering@nordic-fintech-systems.example',
      subject: 'Nordic FinTech Systems: AI operations & automation audit',
      lead_id: 'lead-nordic-fintech',
      draft_id: 'draft-nordic-01',
    },
    created_at: '2026-08-22T22:15:00Z',
    scheduled_at: '2026-08-22T22:15:00Z',
    attempt: 0,
    max_attempts: 1,
    timeout_seconds: 120,
    idempotency_key: 'idemp-email-send-nordic-01',
    depends_on: [],
    evidence_refs: [],
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    lead_id: 'lead-nordic-fintech',
    company: 'Nordic FinTech Systems',
    contact_name: 'Henrik Lindqvist',
    email: 'henrik@nordicfintech.example',
    website: 'https://nordicfintech.example',
    industry: 'Financial Technology',
    problem: 'Manual reconciliation in loan processing causing 3-day turnaround delay',
    team_size: '50-199',
    current_tools: ['PostgreSQL', 'Jira', 'Custom Python', 'Salesforce'],
    urgency: 'high',
    estimated_value: 26100,
    score: 74,
    consent: true,
    source: 'Public regulatory fintech register',
    state: 'draft_ready',
    created_at: '2026-08-21T10:00:00Z',
    updated_at: '2026-08-22T08:30:00Z',
  },
  {
    lead_id: 'lead-apex-logistics',
    company: 'Apex Freight & Logistics',
    contact_name: 'Elena Rostova',
    email: 'elena@apexlogistics.example',
    website: 'https://apexlogistics.example',
    industry: 'Supply Chain & Freight',
    problem: 'Customs declaration document parsing is 100% manual across 4 languages',
    team_size: '200+',
    current_tools: ['SAP', 'OCR Tesseract', 'Email inbox', 'Excel'],
    urgency: 'immediate',
    estimated_value: 54600,
    score: 82,
    consent: true,
    source: 'Logistics trade portal',
    state: 'audit_ready',
    created_at: '2026-08-20T14:15:00Z',
    updated_at: '2026-08-22T09:00:00Z',
  },
  {
    lead_id: 'lead-clarity-med',
    company: 'Clarity Health Analytics',
    contact_name: 'Dr. Marcus Vance',
    email: 'marcus@claritymed.example',
    website: 'https://claritymed.example',
    industry: 'Healthcare Informatics',
    problem: 'Need HIPAA-compliant local model routing for patient triage summary',
    team_size: '10-49',
    current_tools: ['Docker', 'FastAPI', 'Epic EHR', 'AWS S3'],
    urgency: 'medium',
    estimated_value: 7020,
    score: 67,
    consent: false,
    source: 'Public healthcare innovation directory',
    state: 'new',
    created_at: '2026-08-22T16:00:00Z',
    updated_at: '2026-08-22T16:00:00Z',
  },
];
